version: '3'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Pa$$w0rd
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app/wordpress:/var/www/html
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Pa$$w0rd
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./config/mysql:/var/lib/mysql
    networks:
      - backend


  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/nginx:/etc/nginx/conf.d
    networks:
      - frontend

networks:
  frontend:
  backend:
