version: '3'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: Pa$$w0rd
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./app/wordpress:/var/www/html
    networks:
      - backend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: Pa$$w0rd
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./config/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
