version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_DB_USER: ${WORDPRESS_DB_USER}
      MYSQL_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./config/mysql:/var/lib/mysql
    networks:
      - backend

  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./app/wordpress:/var/www/html
    ports:
      - "8080:80"
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./app/nginx:/etc/nginx/conf.d
    networks:
      - frontend

  fastapi-app: # Sources : https://www.youtube.com/watch?v=kAVBNgsrtik
    image: rslim087/fastapi-prometheus:latest
    volumes:
      - ./app/fastapi-app:/fastapi-collection.json
    ports:
      - "8000:8000"  # Assuming your FastAPI app runs on port 8000
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  frontend:
  backend:
